name: LuxEstate

on:
  push:
    branches:
      - main

jobs:
  myDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: For pick the repository
        uses: actions/checkout@v4
      - name: for connection
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

          script: |
            cd /home/sujal/6weeks_Sujal_Python_backend
            git pull origin main
            source venv/bin/activate
            pip install requirements.txt
            pm2 restart backend || pm2 start "uvicorn main:app --host 0.0.0.0 --port 8000" --name backend 
